#!/usr/bin/env php
<?php

echo "Setting up Git-Based-Blog\n";

$exec_name = array_shift($argv);

function file_copy($src, $dest)
{
  file_put_contents($dest, file_get_contents($src));
}

function setup_configuration_file()
{
  if (file_exists("config.php")) {
    print "File config.php already exists. Overwrite? ";
  } else {
    echo " Creating configuration file\n";
    file_copy("config.php.default", "config.php");
  }
}

function install_git_hooks()
{
  if (!file_exists('.git')) {
    printf(stderr, "Error: This appears to not be a git repository, please 'git init'\n");
    exit(1);
  }
  print "Installing git hooks\n";
  file_copy("git_hooks/post_update", ".git/hooks/post_update");
}

if (count($argv) === 0) {
  setup_configuration_file();
  install_git_hooks();
} else {
  var_dump($argv);
}

